# Visit 3.1.4 log file
ScriptVersion = "3.1.4"
if ScriptVersion != Version():
    print "This script is for VisIt %s. It may not work with version %s" % (ScriptVersion, Version())
visit.ShowAllWindows()
DefineScalarExpression("udotn", "U[2]")
OpenDatabase("localhost:/scratch/bistable_helix/data/giesekus/alpha=0.01/De=1.0_temp/viz/dumps.visit", 0)
# The UpdateDBPluginInfo RPC is not supported in the VisIt module so it will not be logged.
SetActivePlots(0)
DeleteActivePlots()
AddPlot("Pseudocolor", "udotn", 1, 1)
AddOperator("Clip", 1)
SetActivePlots(0)
ClipAtts = ClipAttributes()
ClipAtts.quality = ClipAtts.Fast  # Fast, Accurate
ClipAtts.funcType = ClipAtts.Plane  # Plane, Sphere
ClipAtts.plane1Status = 1
ClipAtts.plane2Status = 0
ClipAtts.plane3Status = 0
ClipAtts.plane1Origin = (0, 0, 0)
ClipAtts.plane2Origin = (0, 0, 0)
ClipAtts.plane3Origin = (0, 0, 0)
ClipAtts.plane1Normal = (1, 0, 0)
ClipAtts.plane2Normal = (0, 1, 0)
ClipAtts.plane3Normal = (0, 0, 1)
ClipAtts.planeInverse = 0
ClipAtts.planeToolControlledClipPlane = ClipAtts.Plane1  # None, Plane1, Plane2, Plane3
ClipAtts.center = (0, 0, 0)
ClipAtts.radius = 1
ClipAtts.sphereInverse = 0
SetOperatorOptions(ClipAtts, 0, 1)
SetActivePlots(0)
AddOperator("Slice", 1)
SetActivePlots(0)
SliceAtts = SliceAttributes()
SliceAtts.originType = SliceAtts.Intercept  # Point, Intercept, Percent, Zone, Node
SliceAtts.originPoint = (0, 0, 0)
SliceAtts.originIntercept = 0
SliceAtts.originPercent = 0
SliceAtts.originZone = 0
SliceAtts.originNode = 0
SliceAtts.normal = (0, -1, 0)
SliceAtts.axisType = SliceAtts.YAxis  # XAxis, YAxis, ZAxis, Arbitrary, ThetaPhi
SliceAtts.upAxis = (0, 0, 1)
SliceAtts.project2d = 1
SliceAtts.interactive = 1
SliceAtts.flip = 0
SliceAtts.originZoneDomain = 0
SliceAtts.originNodeDomain = 0
SliceAtts.meshName = "default"
SliceAtts.theta = 0
SliceAtts.phi = 0
SetOperatorOptions(SliceAtts, 1, 1)
SetActivePlots(0)
DrawPlots()
SetTimeSliderState(0)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(1)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(2)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(3)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(4)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(5)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(6)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(7)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(8)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(9)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(10)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(11)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(12)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(13)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(14)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(15)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(16)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(17)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(18)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(19)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(20)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(21)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(22)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(23)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(24)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(25)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(26)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(27)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(28)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(29)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(30)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(31)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(32)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(33)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(34)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(35)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(36)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(37)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(38)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(39)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(40)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(41)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(42)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(43)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(44)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(45)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(46)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(47)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(48)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(49)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(50)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(51)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(52)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(53)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(54)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(55)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(56)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(57)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(58)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(59)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(60)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(61)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(62)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(63)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(64)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(65)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(66)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(67)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(68)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(69)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(70)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(71)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(72)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(73)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(74)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(75)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(76)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(77)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(78)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(79)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(80)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(81)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(82)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(83)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(84)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(85)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(86)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(87)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(88)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(89)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(90)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(91)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(92)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(93)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(94)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(95)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(96)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(97)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(98)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(99)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(100)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(101)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(102)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(103)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(104)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(105)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(106)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(107)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(108)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(109)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(110)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(111)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(112)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(113)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(114)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(115)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(116)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(117)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(118)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(119)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(120)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(121)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(122)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(123)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(124)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(125)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(126)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(127)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(128)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(129)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(130)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(131)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(132)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(133)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(134)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(135)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(136)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(137)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(138)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(139)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(140)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(141)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(142)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(143)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(144)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(145)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(146)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(147)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(148)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(149)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(150)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(151)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(152)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(153)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(154)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(155)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(156)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(157)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(158)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(159)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(160)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(161)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(162)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(163)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(164)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(165)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(166)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(167)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(168)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(169)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(170)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(171)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(172)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(173)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(174)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(175)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(176)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(177)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(178)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(179)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(180)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(181)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(182)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(183)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(184)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(185)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(186)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(187)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(188)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(189)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(190)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(191)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(192)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(193)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(194)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(195)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(196)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(197)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(198)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(199)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(200)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(201)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(202)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(203)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(204)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(205)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(206)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(207)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(208)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(209)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(210)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(211)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(212)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(213)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(214)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(215)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(216)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(217)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(218)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(219)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(220)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(221)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(222)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(223)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(224)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(225)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(226)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(227)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(228)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(229)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(230)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(231)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(232)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(233)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(234)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(235)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(236)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(237)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(238)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(239)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(240)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(241)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(242)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(243)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(244)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(245)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(246)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(247)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(248)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(249)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(250)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(251)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(252)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(253)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(254)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(255)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(256)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(257)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(258)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(259)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(260)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(261)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(262)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(263)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(264)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(265)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(266)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(267)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(268)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(269)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(270)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(271)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(272)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(273)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(274)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(275)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(276)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(277)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(278)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(279)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(280)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(281)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(282)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(283)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(284)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(285)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(286)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(287)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(288)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(289)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(290)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(291)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(292)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(293)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(294)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(295)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(296)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(297)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(298)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(299)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(300)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(301)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(302)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(303)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(304)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(305)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(306)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(307)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(308)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(309)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(310)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(311)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(312)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(313)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(314)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(315)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(316)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(317)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(318)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(319)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(320)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(321)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(322)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(323)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(324)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(325)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(326)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(327)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(328)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(329)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(330)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(331)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(332)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(333)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(334)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(335)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(336)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(337)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(338)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(339)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(340)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(341)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(342)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(343)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(344)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(345)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(346)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(347)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(348)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(349)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(350)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(351)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(352)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(353)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(354)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(355)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(356)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(357)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(358)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(359)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(360)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(361)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(362)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(363)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(364)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(365)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(366)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(367)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(368)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(369)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(370)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(371)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(372)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(373)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(374)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(375)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(376)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(377)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(378)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(379)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(380)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(381)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(382)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(383)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(384)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(385)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(386)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(387)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(388)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(389)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(390)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(391)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(392)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(393)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(394)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(395)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(396)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(397)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(398)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(399)
Query("Time")
Query("Weighted Variable Sum")
SetActivePlots(0)
DeleteActivePlots()
OpenDatabase("localhost:/scratch/bistable_helix/data/giesekus/alpha=0.01/De=1.0_temp/viz/dumps.visit")
OpenDatabase("localhost:/scratch/bistable_helix/data/giesekus/alpha=0.01/De=1.5_temp/viz/dumps.visit", 0)
SetActivePlots(0)
DeleteActivePlots()
AddPlot("Pseudocolor", "udotn", 1, 1)
AddOperator("Clip", 1)
SetActivePlots(0)
ClipAtts = ClipAttributes()
ClipAtts.quality = ClipAtts.Fast  # Fast, Accurate
ClipAtts.funcType = ClipAtts.Plane  # Plane, Sphere
ClipAtts.plane1Status = 1
ClipAtts.plane2Status = 0
ClipAtts.plane3Status = 0
ClipAtts.plane1Origin = (0, 0, 0)
ClipAtts.plane2Origin = (0, 0, 0)
ClipAtts.plane3Origin = (0, 0, 0)
ClipAtts.plane1Normal = (1, 0, 0)
ClipAtts.plane2Normal = (0, 1, 0)
ClipAtts.plane3Normal = (0, 0, 1)
ClipAtts.planeInverse = 0
ClipAtts.planeToolControlledClipPlane = ClipAtts.Plane1  # None, Plane1, Plane2, Plane3
ClipAtts.center = (0, 0, 0)
ClipAtts.radius = 1
ClipAtts.sphereInverse = 0
SetOperatorOptions(ClipAtts, 0, 1)
SetActivePlots(0)
AddOperator("Slice", 1)
SetActivePlots(0)
SliceAtts = SliceAttributes()
SliceAtts.originType = SliceAtts.Intercept  # Point, Intercept, Percent, Zone, Node
SliceAtts.originPoint = (0, 0, 0)
SliceAtts.originIntercept = 0
SliceAtts.originPercent = 0
SliceAtts.originZone = 0
SliceAtts.originNode = 0
SliceAtts.normal = (0, -1, 0)
SliceAtts.axisType = SliceAtts.YAxis  # XAxis, YAxis, ZAxis, Arbitrary, ThetaPhi
SliceAtts.upAxis = (0, 0, 1)
SliceAtts.project2d = 1
SliceAtts.interactive = 1
SliceAtts.flip = 0
SliceAtts.originZoneDomain = 0
SliceAtts.originNodeDomain = 0
SliceAtts.meshName = "default"
SliceAtts.theta = 0
SliceAtts.phi = 0
SetOperatorOptions(SliceAtts, 1, 1)
SetActivePlots(0)
DrawPlots()
SetTimeSliderState(0)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(1)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(2)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(3)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(4)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(5)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(6)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(7)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(8)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(9)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(10)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(11)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(12)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(13)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(14)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(15)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(16)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(17)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(18)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(19)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(20)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(21)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(22)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(23)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(24)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(25)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(26)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(27)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(28)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(29)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(30)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(31)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(32)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(33)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(34)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(35)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(36)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(37)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(38)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(39)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(40)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(41)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(42)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(43)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(44)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(45)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(46)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(47)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(48)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(49)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(50)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(51)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(52)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(53)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(54)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(55)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(56)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(57)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(58)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(59)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(60)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(61)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(62)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(63)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(64)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(65)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(66)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(67)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(68)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(69)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(70)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(71)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(72)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(73)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(74)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(75)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(76)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(77)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(78)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(79)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(80)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(81)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(82)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(83)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(84)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(85)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(86)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(87)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(88)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(89)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(90)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(91)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(92)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(93)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(94)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(95)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(96)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(97)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(98)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(99)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(100)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(101)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(102)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(103)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(104)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(105)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(106)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(107)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(108)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(109)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(110)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(111)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(112)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(113)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(114)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(115)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(116)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(117)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(118)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(119)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(120)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(121)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(122)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(123)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(124)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(125)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(126)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(127)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(128)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(129)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(130)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(131)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(132)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(133)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(134)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(135)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(136)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(137)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(138)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(139)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(140)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(141)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(142)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(143)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(144)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(145)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(146)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(147)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(148)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(149)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(150)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(151)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(152)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(153)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(154)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(155)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(156)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(157)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(158)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(159)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(160)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(161)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(162)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(163)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(164)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(165)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(166)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(167)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(168)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(169)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(170)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(171)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(172)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(173)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(174)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(175)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(176)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(177)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(178)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(179)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(180)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(181)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(182)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(183)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(184)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(185)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(186)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(187)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(188)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(189)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(190)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(191)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(192)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(193)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(194)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(195)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(196)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(197)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(198)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(199)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(200)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(201)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(202)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(203)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(204)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(205)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(206)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(207)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(208)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(209)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(210)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(211)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(212)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(213)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(214)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(215)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(216)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(217)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(218)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(219)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(220)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(221)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(222)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(223)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(224)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(225)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(226)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(227)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(228)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(229)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(230)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(231)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(232)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(233)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(234)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(235)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(236)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(237)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(238)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(239)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(240)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(241)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(242)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(243)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(244)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(245)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(246)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(247)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(248)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(249)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(250)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(251)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(252)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(253)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(254)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(255)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(256)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(257)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(258)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(259)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(260)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(261)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(262)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(263)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(264)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(265)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(266)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(267)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(268)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(269)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(270)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(271)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(272)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(273)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(274)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(275)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(276)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(277)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(278)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(279)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(280)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(281)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(282)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(283)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(284)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(285)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(286)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(287)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(288)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(289)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(290)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(291)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(292)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(293)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(294)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(295)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(296)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(297)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(298)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(299)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(300)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(301)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(302)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(303)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(304)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(305)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(306)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(307)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(308)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(309)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(310)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(311)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(312)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(313)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(314)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(315)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(316)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(317)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(318)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(319)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(320)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(321)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(322)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(323)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(324)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(325)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(326)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(327)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(328)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(329)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(330)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(331)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(332)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(333)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(334)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(335)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(336)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(337)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(338)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(339)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(340)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(341)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(342)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(343)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(344)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(345)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(346)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(347)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(348)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(349)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(350)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(351)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(352)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(353)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(354)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(355)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(356)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(357)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(358)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(359)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(360)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(361)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(362)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(363)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(364)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(365)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(366)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(367)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(368)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(369)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(370)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(371)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(372)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(373)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(374)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(375)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(376)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(377)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(378)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(379)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(380)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(381)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(382)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(383)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(384)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(385)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(386)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(387)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(388)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(389)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(390)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(391)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(392)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(393)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(394)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(395)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(396)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(397)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(398)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(399)
Query("Time")
Query("Weighted Variable Sum")
SetActivePlots(0)
DeleteActivePlots()
OpenDatabase("localhost:/scratch/bistable_helix/data/giesekus/alpha=0.01/De=1.5_temp/viz/dumps.visit")
OpenDatabase("localhost:/scratch/bistable_helix/data/giesekus/alpha=0.01/De=2.0_temp/viz/dumps.visit", 0)
SetActivePlots(0)
DeleteActivePlots()
AddPlot("Pseudocolor", "udotn", 1, 1)
AddOperator("Clip", 1)
SetActivePlots(0)
ClipAtts = ClipAttributes()
ClipAtts.quality = ClipAtts.Fast  # Fast, Accurate
ClipAtts.funcType = ClipAtts.Plane  # Plane, Sphere
ClipAtts.plane1Status = 1
ClipAtts.plane2Status = 0
ClipAtts.plane3Status = 0
ClipAtts.plane1Origin = (0, 0, 0)
ClipAtts.plane2Origin = (0, 0, 0)
ClipAtts.plane3Origin = (0, 0, 0)
ClipAtts.plane1Normal = (1, 0, 0)
ClipAtts.plane2Normal = (0, 1, 0)
ClipAtts.plane3Normal = (0, 0, 1)
ClipAtts.planeInverse = 0
ClipAtts.planeToolControlledClipPlane = ClipAtts.Plane1  # None, Plane1, Plane2, Plane3
ClipAtts.center = (0, 0, 0)
ClipAtts.radius = 1
ClipAtts.sphereInverse = 0
SetOperatorOptions(ClipAtts, 0, 1)
SetActivePlots(0)
AddOperator("Slice", 1)
SetActivePlots(0)
SliceAtts = SliceAttributes()
SliceAtts.originType = SliceAtts.Intercept  # Point, Intercept, Percent, Zone, Node
SliceAtts.originPoint = (0, 0, 0)
SliceAtts.originIntercept = 0
SliceAtts.originPercent = 0
SliceAtts.originZone = 0
SliceAtts.originNode = 0
SliceAtts.normal = (0, -1, 0)
SliceAtts.axisType = SliceAtts.YAxis  # XAxis, YAxis, ZAxis, Arbitrary, ThetaPhi
SliceAtts.upAxis = (0, 0, 1)
SliceAtts.project2d = 1
SliceAtts.interactive = 1
SliceAtts.flip = 0
SliceAtts.originZoneDomain = 0
SliceAtts.originNodeDomain = 0
SliceAtts.meshName = "default"
SliceAtts.theta = 0
SliceAtts.phi = 0
SetOperatorOptions(SliceAtts, 1, 1)
SetActivePlots(0)
DrawPlots()
SetTimeSliderState(0)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(1)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(2)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(3)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(4)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(5)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(6)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(7)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(8)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(9)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(10)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(11)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(12)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(13)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(14)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(15)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(16)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(17)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(18)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(19)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(20)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(21)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(22)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(23)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(24)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(25)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(26)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(27)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(28)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(29)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(30)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(31)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(32)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(33)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(34)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(35)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(36)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(37)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(38)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(39)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(40)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(41)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(42)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(43)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(44)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(45)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(46)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(47)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(48)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(49)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(50)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(51)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(52)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(53)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(54)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(55)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(56)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(57)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(58)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(59)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(60)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(61)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(62)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(63)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(64)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(65)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(66)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(67)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(68)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(69)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(70)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(71)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(72)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(73)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(74)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(75)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(76)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(77)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(78)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(79)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(80)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(81)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(82)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(83)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(84)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(85)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(86)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(87)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(88)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(89)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(90)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(91)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(92)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(93)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(94)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(95)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(96)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(97)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(98)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(99)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(100)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(101)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(102)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(103)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(104)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(105)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(106)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(107)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(108)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(109)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(110)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(111)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(112)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(113)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(114)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(115)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(116)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(117)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(118)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(119)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(120)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(121)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(122)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(123)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(124)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(125)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(126)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(127)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(128)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(129)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(130)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(131)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(132)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(133)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(134)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(135)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(136)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(137)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(138)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(139)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(140)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(141)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(142)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(143)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(144)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(145)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(146)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(147)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(148)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(149)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(150)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(151)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(152)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(153)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(154)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(155)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(156)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(157)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(158)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(159)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(160)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(161)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(162)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(163)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(164)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(165)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(166)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(167)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(168)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(169)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(170)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(171)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(172)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(173)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(174)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(175)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(176)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(177)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(178)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(179)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(180)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(181)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(182)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(183)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(184)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(185)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(186)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(187)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(188)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(189)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(190)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(191)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(192)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(193)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(194)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(195)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(196)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(197)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(198)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(199)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(200)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(201)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(202)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(203)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(204)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(205)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(206)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(207)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(208)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(209)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(210)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(211)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(212)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(213)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(214)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(215)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(216)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(217)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(218)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(219)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(220)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(221)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(222)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(223)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(224)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(225)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(226)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(227)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(228)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(229)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(230)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(231)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(232)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(233)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(234)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(235)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(236)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(237)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(238)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(239)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(240)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(241)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(242)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(243)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(244)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(245)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(246)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(247)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(248)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(249)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(250)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(251)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(252)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(253)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(254)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(255)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(256)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(257)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(258)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(259)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(260)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(261)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(262)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(263)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(264)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(265)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(266)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(267)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(268)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(269)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(270)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(271)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(272)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(273)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(274)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(275)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(276)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(277)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(278)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(279)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(280)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(281)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(282)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(283)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(284)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(285)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(286)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(287)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(288)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(289)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(290)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(291)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(292)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(293)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(294)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(295)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(296)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(297)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(298)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(299)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(300)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(301)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(302)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(303)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(304)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(305)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(306)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(307)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(308)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(309)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(310)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(311)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(312)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(313)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(314)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(315)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(316)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(317)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(318)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(319)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(320)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(321)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(322)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(323)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(324)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(325)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(326)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(327)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(328)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(329)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(330)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(331)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(332)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(333)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(334)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(335)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(336)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(337)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(338)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(339)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(340)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(341)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(342)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(343)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(344)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(345)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(346)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(347)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(348)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(349)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(350)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(351)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(352)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(353)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(354)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(355)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(356)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(357)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(358)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(359)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(360)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(361)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(362)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(363)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(364)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(365)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(366)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(367)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(368)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(369)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(370)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(371)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(372)
Query("Time")
Query("Weighted Variable Sum")
SetTimeSliderState(373)
Query("Time")
Query("W